sudo: required

services:
  - docker

language: cpp

before_install:
  - cd ..
  - cp gcm-3d/tools/docker/travis-ci-tests/run_tests.sh .
  - docker build -t fufler/gcm3d-travis-ci-tests -f gcm-3d/tools/docker/travis-ci-tests/Dockerfile .

script:
  - docker run fufler/gcm3d-travis-ci-tests /bin/sh /root/gcm-3d/run_tests.sh
branches:
  only:
    - master

notifications:
  email: false
